// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Olimpeadas.Infraestructure.Data;

#nullable disable

namespace Olimpeadas.Infraestructure.Data.Migrations
{
    [DbContext(typeof(OlimpeadasDbContext))]
    [Migration("20260923192748_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Olimpeadas.Domain.Entities.Alerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Latitud")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitud")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Alertas");
                });

            modelBuilder.Entity("Olimpeadas.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Olimpeadas.Domain.Entities.Contacto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MunicipioId")
                        .HasColumnType("integer");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("MunicipioId");

                    b.ToTable("Contactos");
                });

            modelBuilder.Entity("Olimpeadas.Domain.Entities.Direccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Calle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Latitud")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitud")
                        .HasColumnType("decimal(9,6)");

                    b.HasKey("Id");

                    b.ToTable("Direcciones");
                });

            modelBuilder.Entity("Olimpeadas.Domain.Entities.HistorialEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .HasColumnType("text");

                    b.Property<string>("EstadoAnterior")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("EstadoNuevo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReporteId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReporteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("HistorialesEstado");
                });

            modelBuilder.Entity("Olimpeadas.Domain.Entities.Imagen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ReporteId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("ReporteId");

                    b.ToTable("Imagenes");
                });

            modelBuilder.Entity("Olimpeadas.Domain.Entities.Municipio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Municipios");
                });

            modelBuilder.Entity("Olimpeadas.Domain.Entities.Noticia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MunicipioId")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("MunicipioId");

                    b.ToTable("Noticias");
                });

            modelBuilder.Entity("Olimpeadas.Domain.Entities.Registro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NoticiaId")
                        .HasColumnType("integer");

                    b.Property<int>("ReporteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NoticiaId");

                    b.HasIndex("ReporteId", "NoticiaId")
                        .IsUnique();

                    b.ToTable("Registros");
                });

            modelBuilder.Entity("Olimpeadas.Domain.Entities.Reporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DireccionId")
                        .HasColumnType("integer");

                    b.Property<int?>("EmpleadoEncargadoId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("DireccionId");

                    b.HasIndex("EmpleadoEncargadoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("Olimpeadas.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ContraseñaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("MunicipioId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.HasKey("Id");

                    b.HasIndex("DNI")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MunicipioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Olimpeadas.Domain.Entities.UsuarioAlerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlertaId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlertaId");

                    b.HasIndex("UsuarioId", "AlertaId")
                        .IsUnique();

                    b.ToTable("UsuariosAlertas");
                });

            modelBuilder.Entity("Olimpeadas.Domain.Entities.Contacto", b =>
                {
                    b.HasOne("Olimpeadas.Domain.Entities.Municipio", "Municipio")
                        .WithMany("Contactos")
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("Olimpeadas.Domain.Entities.HistorialEstado", b =>
                {
                    b.HasOne("Olimpeadas.Domain.Entities.Reporte", "Reporte")
                        .WithMany("HistorialesEstado")
                        .HasForeignKey("ReporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Olimpeadas.Domain.Entities.Usuario", "Usuario")
                        .WithMany("HistorialesEstado")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reporte");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Olimpeadas.Domain.Entities.Imagen", b =>
                {
                    b.HasOne("Olimpeadas.Domain.Entities.Reporte", "Reporte")
                        .WithMany("Imagenes")
                        .HasForeignKey("ReporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reporte");
                });

            modelBuilder.Entity("Olimpeadas.Domain.Entities.Noticia", b =>
                {
                    b.HasOne("Olimpeadas.Domain.Entities.Municipio", "Municipio")
                        .WithMany("Noticias")
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("Olimpeadas.Domain.Entities.Registro", b =>
                {
                    b.HasOne("Olimpeadas.Domain.Entities.Noticia", "Noticia")
                        .WithMany("Registros")
                        .HasForeignKey("NoticiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Olimpeadas.Domain.Entities.Reporte", "Reporte")
                        .WithMany("Registros")
                        .HasForeignKey("ReporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Noticia");

                    b.Navigation("Reporte");
                });

            modelBuilder.Entity("Olimpeadas.Domain.Entities.Reporte", b =>
                {
                    b.HasOne("Olimpeadas.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Reportes")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Olimpeadas.Domain.Entities.Direccion", "Direccion")
                        .WithMany("Reportes")
                        .HasForeignKey("DireccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Olimpeadas.Domain.Entities.Usuario", "EmpleadoEncargado")
                        .WithMany("ReportesAsignados")
                        .HasForeignKey("EmpleadoEncargadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Olimpeadas.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Reportes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Direccion");

                    b.Navigation("EmpleadoEncargado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Olimpeadas.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Olimpeadas.Domain.Entities.Municipio", "Municipio")
                        .WithMany("Usuarios")
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("Olimpeadas.Domain.Entities.UsuarioAlerta", b =>
                {
                    b.HasOne("Olimpeadas.Domain.Entities.Alerta", "Alerta")
                        .WithMany("UsuariosAlertas")
                        .HasForeignKey("AlertaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Olimpeadas.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuariosAlertas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alerta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Olimpeadas.Domain.Entities.Alerta", b =>
                {
                    b.Navigation("UsuariosAlertas");
                });

            modelBuilder.Entity("Olimpeadas.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Reportes");
                });

            modelBuilder.Entity("Olimpeadas.Domain.Entities.Direccion", b =>
                {
                    b.Navigation("Reportes");
                });

            modelBuilder.Entity("Olimpeadas.Domain.Entities.Municipio", b =>
                {
                    b.Navigation("Contactos");

                    b.Navigation("Noticias");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Olimpeadas.Domain.Entities.Noticia", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("Olimpeadas.Domain.Entities.Reporte", b =>
                {
                    b.Navigation("HistorialesEstado");

                    b.Navigation("Imagenes");

                    b.Navigation("Registros");
                });

            modelBuilder.Entity("Olimpeadas.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("HistorialesEstado");

                    b.Navigation("Reportes");

                    b.Navigation("ReportesAsignados");

                    b.Navigation("UsuariosAlertas");
                });
#pragma warning restore 612, 618
        }
    }
}
